### ISSUE TITLE
prepare for webpack 2

### ISSUE THREAD

**Issue by gasolin** [mozilla-neutrino/neutrino-preset-base#10]
Since webpack 2 is in beta, it might worth to start working on it now, it will be a nice marketing point when webpack 2 is official released and neutrino-preset-xx are the easiest way to reuse related settings.

http://javascriptplayground.com/blog/2016/10/moving-to-webpack-2/

**Comment by eliperelman** [comment]
Totally. Right now @helfi92 is working on getting things migrated to Webpack 2 and adding more optimization changes to the presets.

**Comment by eliperelman** [comment]
This has been mostly completed in neutrino-dev.
