### ISSUE TITLE
add cross-env to support setting PORT in npm script

### ISSUE THREAD

**Issue by gasolin** [mozilla-neutrino/neutrino-preset-base#5]
set ENV in script is not support on windows, so `"PORT=4000 neutrino start"` won't work.

We can use cross-env to set single ENV in any platform. Therefore the workable cross-platform start script would be 

`"start": "cross-env PORT=4000 neutrino start",`

**Comment by eliperelman** [comment]
Actually, now that I think about it, this is not the job of neutrino or its presets. This should live in the dependent project

```json
{
  "dependencies": {
    "cross-env": "*",
    "neutrino": "*",
    "neutrino-preset-web": "*"
  },
  "scripts": {
    "start": "cross-env PORT=3000 neutrino start -p neutrino-preset-web
  }
}
```

**Comment by gasolin** [comment]
I was thinking add PORT env is necessary due to the doc. I found its optional after reading code(default port is 5000). So the right patch might be change the readme to not include port env setting in npm start script
